config/routes.rb
Rails.application.routes.draw do
  require "sidekiq/web"
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users
  root to: "pages#home"

  mount Sidekiq::Web => '/sidekiq'
  mount StripeEvent::Engine, at: '/stripe-webhooks'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check


  # Defines the root path route ("/")
  # root "posts#index"
  resources :shelters, only: [:index, :show] do
    resources :pets, only: [:new, :create]
  end
  resources :pages do
    collection do
      get 'dashboard'
    end
  end
  resources :chatrooms, only: [:show, :new, :create, :index] do
    resources :messages, only: [:create, :destroy]
  end
  resources :pets, only: [:show] do
    member do
      post 'feed'
      post 'play'
      post 'care'
    end
  end

  get 'faqs', to: 'pages#faq'

  resources :users, only: [:update]
  resources :orders, only: [:show, :create] do
    resources :payments, only: :new
  end
end

app/models/shelter.rb
class Shelter < ApplicationRecord
  has_many :pets, dependent: :destroy
  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?
  has_one_attached :photo
end

app/controllers/shelters_controller.rb
class SheltersController < ApplicationController
  before_action :set_shelter, only: [:show]

  def index
    @shelters = Shelter.all
    @user = current_user
    @favourite_shelter = @user.pets


    if params[:address].present?
      @shelters = @shelters.near(params[:address])
    end

    @markers = @shelters.geocoded.map do |shelter|
      {
        lat: shelter.latitude,
        lng: shelter.longitude,
        info_window_html: render_to_string(partial: "info_window", locals: { shelter: shelter }),
        marker_html: render_to_string(partial: "marker", locals: { shelter: shelter })
      }
    end
  end

  def show
  end

  private

  def set_shelter
    @shelter = Shelter.find(params[:id])
  end
end

app/views/shelters/_form.html.erb
<div data-controller="address-autocomplete" data-address-autocomplete-api-key-value=<%=ENV["MAPBOX_API_KEY"]%>>
<%= f.text_field :address,
  {data: {address_autocomplete_target: "address"}, class: "d-none"}
%>
</div>

app/views/shelters/_info_window.html.erb
<h2><%= shelter.name %></h2>
<p><%= shelter.address %></p>

app/views/shelters/_marker.html.erb
<dotlottie-player src="https://lottie.host/46edb004-b7f2-4b57-988c-6ea96f1d0187/NtVza3K583.json"
background="transparent" speed="1"
style="width: 75px; height: 75px;" loop autoplay></dotlottie-player>

app/views/shelters/index.html.erb
<script src="https://unpkg.com/@dotlottie/player-component@latest/dist/dotlottie-player.mjs" type="module"></script>


<div style="width: 100%; height: 800px;"
  data-controller="map"
  data-map-markers-value="<%= @markers.to_json %>"
  data-map-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>"></div>

<br>
<br>
<div class="container" id="bg-cards">
  <div class="row map-cards">
    <% @shelters.each do |shelter| %>
      <div class="col-lg-4 col-md-6 mb-4">
        <div class="card-shelter">
          <div class="card-shelter-infos">
            <%= cl_image_tag shelter.photo.key, height: 300, width: 400, crop: :fill %>
            <div class="mark">
            <% @favourite_shelter.each do |favourite| %>
              <% if (favourite.shelter == shelter) %>
                <i class="fa-solid fa-hand-holding-heart" aria-describedby="info">
                </i>
                <div role="tooltip" id="info">
                <p>you're already donating to this shelter!</p>
              </div>
              <% break %>
              <% end %>
            <% end %>

            </div>

            <h2> <%= shelter.name %> </h2>
              <em><i class="fas fa-map-marker-alt point"></i><%= shelter.address %> </em>
            <p> <%= shelter.description %> </p>
            <div class="d-flex shelter-buttons">
              <div class="p-2"><%= link_to "Donate", new_shelter_pet_path(shelter), class:"secondary-button" %></div>
              <div class="p-2"><%= link_to "Discover", new_shelter_pet_path(shelter), class:"tertiary-button" %></div>
            </div>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>