config/routes.rb
Rails.application.routes.draw do
  require "sidekiq/web"
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users
  root to: "pages#home"

  mount Sidekiq::Web => '/sidekiq'
  mount StripeEvent::Engine, at: '/stripe-webhooks'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check


  # Defines the root path route ("/")
  # root "posts#index"
  resources :shelters, only: [:index, :show] do
    resources :pets, only: [:new, :create]
  end
  resources :pages do
    collection do
      get 'dashboard'
    end
  end
  resources :chatrooms, only: [:show, :new, :create, :index] do
    resources :messages, only: [:create, :destroy]
  end
  resources :pets, only: [:show] do
    member do
      post 'feed'
      post 'play'
      post 'care'
    end
  end

  get 'faqs', to: 'pages#faq'

  resources :users, only: [:update]
  resources :orders, only: [:show, :create] do
    resources :payments, only: :new
  end
end

app/models/pet.rb
class Pet < ApplicationRecord
  def set_default_levels
    self.food_level ||= 80
    self.satisfaction ||= 95
    self.health ||= 100
    self.boredom ||= 0
  end

  belongs_to :user
  belongs_to :shelter

  has_many :orders, dependent: :destroy
  has_one_attached :picture


  before_create :set_default_levels
  def picture_url
    if species == 'cat'
      'cat.png'
    elsif species == 'dog'
      'dog.png'
    else
      'puppy-test'
    end
  end

end

app/controllers/pets_controller.rb
class PetsController < ApplicationController
  before_action :set_pet, only:[:show, :feed, :play, :care]

  def show
    # passive_decrease
    # @pet.save
    @food_items = Item.where(category: "food")
    @toy_items = Item.where(category: "toy")
    @medical_items = Item.where(category: "medical")
    render footer: false
  end

  def new
    @pet = Pet.new
    @shelter = Shelter.find(params[:shelter_id])
  end

  def create
    @shelter = Shelter.find(params[:shelter_id])
    @pet = Pet.new(pet_params)
    @pet.user = current_user
    @pet.shelter = @shelter
    if @pet.save
      redirect_to @pet
    else
      render :new
    end
  end

  def feed
    change_levels(20, 5, -5)
    redirect_to @pet
  end

  def play
    change_levels(0, 5, -10)
    redirect_to @pet
  end

  def care
    change_levels(0, 0, -5)
    @pet.health = [@pet.health + 10, 100].min
    @pet.save
    redirect_to @pet
  end

  def pets_random_message
    if pet.downcase == 'dog'
      dog_messages = [
        "The Akita is a majestic and loyal breed originating from Japan. Known for their dignified presence and striking appearance, Akitas possess a strong and independent nature.",
        "Akitas are fiercely protective of their families and make devoted companions, but they require experienced handling and early socialization to thrive.",
      ]
      return dog_messages.sample
    elsif pet.downcase == 'cat'
      cat_messages = [
        "The Maine Coon, America's native long-haired breed, is a charming and gentle giant among cats. Renowned for their large size, tufted ears, and bushy tails, Maine Coons have a friendly and sociable disposition.",
        "With their playful antics and affectionate nature, they easily integrate into family life. These intelligent cats are excellent hunters and enjoy interactive play.",
      ]
      return cat_messages.sample
    end
  end

  private

  def set_pet
    @pet = Pet.find(params[:id])
  end

  def pet_params
    params.require(:pet).permit(:name, :species)
  end

  # Method to change levels for feed, play, and care actions
  def change_levels(food, satisfaction, boredom)
    @pet.food_level = [@pet.food_level + food, 100].min
    @pet.satisfaction = [[@pet.satisfaction + satisfaction, 10].max, 100].min
    @pet.boredom = [[@pet.boredom + boredom, 0].max, 100].min
    @pet.save
  end

  # Method to passively decrease satisfaction and increase boredom
  # def passive_decrease
   # @pet.food_level = [@pet.food_level - 1, 0].max
    #@pet.satisfaction = [[@pet.satisfaction - 1, 10].max, 100].min
   # @pet.boredom = [@pet.boredom + 1, 100].min
 # end
end

app/views/pets/_form.html.erb
<%= form_with url: orders_path do %>
  <%= hidden_field_tag 'item_id', item.id %>
  <%= hidden_field_tag 'pet_id', pet.id %>
  <%= button_tag(type: 'submit', class: 'pet-show-button') do %>
    Donate!
  <% end %>
<% end %>

app/views/pets/new.html.erb
<div class="container d-flex m-auto">
<div class="d-flex create-pet-container flex-column justify-content-center align-self-center m-auto">

  <div class="d-flex justify-content-center py-5">
    <h1>Let's adopt a virtual pet!</h1>
  </div>
  <%= simple_form_for [@shelter, @pet], html: { autocomplete: 'off' }, defaults: { label: false } do |f| %>
  <div
   class="d-flex pet-form p-2"
   data-controller="sounds"
   data-sounds-cat-value=<%= audio_url("cat-sound.mp3")%>
   data-sounds-dog-value=<%=  audio_url("dog-sound.mp3")%> >
    <i class="fa-solid fa-paw p-2"></i>
    <h5 class="p-2"> Choose your pet: </h5>
    <%= f.input_field :species, as: :radio_buttons,
      collection: [['dog', (image_tag "shiba 1.png", alt: "Dog", class:"photo-pet", data: {action:"click->sounds#playDog"})],
                   ['cat', (image_tag "blackCat 1.png", alt: "Cat", class:"photo-pet", data: {action:"click->sounds#playCat"})]
                  ], label_method: :second,
      value_method: :first %>
  </div>

  <div class="d-flex p-2 pet-form">
    <i class="fa-solid fa-paw p-2"></i>
    <h5 class="p-2 pr-4"> Choose a name: </h5>
    <div class="p-2 pet-name">
      <%= f.input :name,
        error: 'A name is mandatory, please specify one',
        input_html: { maxlength: 20, style: "border-radius: 20px; width: 400px;" } %>
    </div>
  </div>

  <div class="d-flex justify-content-around align-items-center py-5">
    <%= link_to "Back", shelters_path, class:"tertiary-button" %>
    <%= f.button :submit, class: "secondary-button" %>
  </div>
  <% end %>
</div>
</div>

app/views/pets/show.html.erb
<div>
  <div class="pet-name"><h2><%= @pet.name %></h2></div>
  <div class="pet-display">
    <div class="show-stats">
      <div class="status-item">
        <div id="satisfaction-circle" class="donut" style="<%="background: conic-gradient(#e45e05 #{@pet.satisfaction}%, rgba(255, 255, 255, 0.5) 0 100%);"%>">
          <div id="satisfaction-gap" class="donut__gap"><p align="center">Satisfaction <%=@pet.satisfaction%>%</p></div>
          </div>
        </div>

        <div class="status-item">
          <div class="donut" style="<%="background: conic-gradient(#D9D9D9 #{@pet.food_level}%, rgba(255, 255, 255, 0.5) 0 100%);"%>">
          <div class="donut__gap"><p align="center">Food Level <br><%=@pet.food_level%>%</p></div>
          </div>
        </div>

        <div class="status-item">
          <div class="donut" style="<%="background: conic-gradient(#D9D9D9 #{@pet.boredom}%, rgba(255, 255, 255, 0) 0 100%);"%>">
          <div class="donut__gap"><p align="center">Boredom <br><%=@pet.boredom%>%</p></div>
          </div>
        </div>

        <div class="status-item">
          <div class="donut" style="<%="background: conic-gradient(#D9D9D9 #{@pet.health}%, rgba(255, 255, 255, 0) 0 100%);"%>">
          <div class="donut__gap"><p align="center">Health <br><%=@pet.health%>%</p></div>
            </div>
        </div>
      </div>
    <div class="pet-image">
      <% if @pet.species == 'dog'%>
        <script src="https://unpkg.com/@dotlottie/player-component@latest/dist/dotlottie-player.mjs" type="module"></script>
        <dotlottie-player src="https://lottie.host/2c482328-02f3-40fd-8ac5-b7043be3fb2f/T8xThR2QCD.json" background="transparent" speed="1" style="width: 300px; height: 300px;" loop autoplay></dotlottie-player>
      <% elsif @pet.species == 'cat'%>
        <div class="cat-div">
          <script src="https://unpkg.com/@dotlottie/player-component@latest/dist/dotlottie-player.mjs" type="module"></script>
          <dotlottie-player src="https://lottie.host/bb79c63e-1966-40f6-bc72-fa5e68cb0fca/t1pob5ccCQ.json" background="transparent" speed="1" style="width: 300px; height: 300px;" loop autoplay></dotlottie-player>
        </div>
      <%end%>
    </div>
    <div class="pet-message">
      <p>
        <% if @pet.satisfaction == 100 %>
          It's great, I am happy!
        <% elsif @pet.satisfaction >= 75 %>
          I'm pretty content!
        <% elsif @pet.satisfaction >= 50 %>
          I'm okay, could be better.
        <% elsif @pet.satisfaction >= 25 %>
          I'm feeling a bit low.
        <% else %>
          I'm really sad, please cheer me up!
        <% end %>
      </p></div>
  </div>
  <div class="pet-actions-container" data-controller="donation">

    <div class="pet-actions">
        <button class="dog-food-icon" data-action="click->donation#openCards">
          <%= image_tag 'dog-food.jpg', class:"food-icon"%>
        </button>

        <button class="dog-toy-icon" data-action="click->donation#openCards">
          <%= image_tag 'dog-toy.png', class:"toy-icon"%>
        </button>

        <button class="dog-medical-icon" data-action="click->donation#openCards">
          <%= image_tag 'health-care.png', class:"health-icon"%>
        </button>
    </div>
    <div class="pet-item-actions">
      <div class="food-items">

        <div data-donation-target="foodItems" class="food-display d-none">

          <% @food_items.each do |item| %>

            <div class="card-product">
              <div class="card-product-infos">
                <h2> <%= item.name %> </h2>
                <p> Donate <strong><%= humanized_money_with_symbol(item.price) %> - </strong> <%= item.description %> </p>
                <% if item.price == 0 %>
                  <%= button_to 'Donate!', feed_pet_path(@pet), method: :post, class:"pet-show-button" %>
                <% else %>
                  <%= render 'pets/form', item: item, pet: @pet %>
                <% end %>
              </div>
            </div>
          <% end %>

        </div>
      </div>

      <div class="toy-items">

        <div data-donation-target="toyItems" class="toy-display d-none">

          <% @toy_items.each do |item| %>

            <div class="card-product">
              <div class="card-product-infos">
                <h2> <%= item.name %> </h2>
                <p> Donate <strong> <%= humanized_money_with_symbol(item.price) %> - </strong> <%= item.description %> </p>
                <% if item.price == 0 %>
                  <%= button_to 'Donate!', play_pet_path(@pet), method: :post, class:"pet-show-button" %>
                <% else %>
                  <%= render 'pets/form', item: item, pet: @pet %>
                <% end %>
              </div>
            </div>
          <% end %>

        </div>
      </div>

      <div class="medical-items">

        <div data-donation-target="medicalItems" class="health-display d-none">

          <% @medical_items.each do |item| %>

            <div class="card-product">
              <div class="card-product-infos">
                <h2> <%= item.name %> </h2>
                <p> Donate <strong> <%= humanized_money_with_symbol(item.price) %> - </strong> <%= item.description %> </p>
                <% if item.price == 0 %>
                  <%= button_to 'Donate!', care_pet_path(@pet), method: :post, class:"pet-show-button" %>
                <% else %>
                  <%= render 'pets/form', item: item, pet: @pet %>
                <% end %>
              </div>
            </div>
          <% end %>

        </div>
      </div>

    </div>
  </div>
</div>