config/routes.rb
Rails.application.routes.draw do
  require "sidekiq/web"
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users
  root to: "pages#home"

  mount Sidekiq::Web => '/sidekiq'
  mount StripeEvent::Engine, at: '/stripe-webhooks'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check


  # Defines the root path route ("/")
  # root "posts#index"
  resources :shelters, only: [:index, :show] do
    resources :pets, only: [:new, :create]
  end
  resources :pages do
    collection do
      get 'dashboard'
    end
  end
  resources :chatrooms, only: [:show, :new, :create, :index] do
    resources :messages, only: [:create, :destroy]
  end
  resources :pets, only: [:show] do
    member do
      post 'feed'
      post 'play'
      post 'care'
    end
  end

  get 'faqs', to: 'pages#faq'

  resources :users, only: [:update]
  resources :orders, only: [:show, :create] do
    resources :payments, only: :new
  end
end

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<footer class="footer">
  <div class="footer-content">
    <div class="footer-section">
       <%= image_tag "LogoWhite.png", width: 300 %>
    </div>

    <div class="footer-section">
      <p class="footer-title"><strong>More information</strong><p>
      <ul>
        <li><%= link_to 'Map', shelters_path %></li>
        <li><%= link_to 'Our value proposition', root_path %></li>
        <li><%= link_to 'Join us', new_user_session_path %></li>
        <li><%= link_to 'Profile', dashboard_pages_path %></li>
      </ul>
    </div>

    <div class="footer-section">
      <p class="footer-title"><strong>Stay in contact</strong><p>
      <ul>
        <li><a href="mailto:info@contact.com">info@contact.com</a></li>
        <li><a href="tel:+34654654654">+34 654 654 654</a></li>
      </ul>
    </div>
  </div>

  <div class="footer-bottom">
    <p>Wagon © 2024. All rights reserved</p>
    <ul>
      <li><%= link_to 'Privacy Policy'," #" %></li>
      <li><%= link_to 'Cookies', "#" %></li>
      <li><%= link_to 'Legal Advice', "#" %></li>
      <li><%= link_to 'FAQ', faqs_path %></li>
    </ul>
    <p>Made with ❤️ by the Furry Friend Team</p>
  </div>
</footer>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">
    <%= link_to root_path, class: "navbar-brand" do %>
      <%= image_tag "logo.png", width: 264 %>
    <% end %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="navbar-menu">
      <div class="navbar-item">
        <%= form_with url: shelters_path, method: :get, local: true, class: "d-flex" do |f| %>
          <!-- <%= text_field_tag :search, nil, placeholder: "&#xF002; Find the shelter", aria: { label: 'Search' } %> -->
          <!--<input type="text" placeholder="&#xF002; Search" style="border-radius: 20px; padding: 8px 16px; border: solid #e0dfdf 2px" />
          <input type="text" placeholder="&#xF041  Country, city or zip code   " style="border-radius: 20px; padding: 8px 16px; border: solid #e0dfdf 2px" />
           <%= text_field_tag :location, nil, placeholder: '&#xF3C5 Country, city or zip code &#xF041', aria: { label: 'Location' } %> -->
<%= render"shelters/form", f: f %>
          <%= button_tag type:'submit', class:'tertiary-button' do %>
            Search
          <% end %>
        <% end %>
      </div>
    </div>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <% if user_signed_in? %>
          <li class="nav-item dropdown">
          <% if current_user.avatar.attached?%>
              <%= cl_image_tag current_user.avatar.key, class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
            <% else %>
              <%= image_tag "cat-paw.jpg", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
            <% end %>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "Profile", dashboard_pages_path, class: "dropdown-item" %>

              <%= link_to "Messages", chatroom_path(@general), class: "dropdown-item" %>

              <%= link_to "Log out", destroy_user_session_path, data:{turbo_method: :delete}, class:"dropdown-item"  %>
            </div>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>