config/routes.rb
Rails.application.routes.draw do
  require "sidekiq/web"
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users
  root to: "pages#home"

  mount Sidekiq::Web => '/sidekiq'
  mount StripeEvent::Engine, at: '/stripe-webhooks'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check


  # Defines the root path route ("/")
  # root "posts#index"
  resources :shelters, only: [:index, :show] do
    resources :pets, only: [:new, :create]
  end
  resources :pages do
    collection do
      get 'dashboard'
    end
  end
  resources :chatrooms, only: [:show, :new, :create, :index] do
    resources :messages, only: [:create, :destroy]
  end
  resources :pets, only: [:show] do
    member do
      post 'feed'
      post 'play'
      post 'care'
    end
  end

  get 'faqs', to: 'pages#faq'

  resources :users, only: [:update]
  resources :orders, only: [:show, :create] do
    resources :payments, only: :new
  end
end

app/views/pages/_form_picture.html.erb
<%= simple_form_for(@user) do |f| %>
    <%= f.input :avatar, as: :file %>
    <%= f.submit class:"secondary-button" %>
    <%end%>

app/views/pages/dashboard.html.erb
<div class="container-dashboard">
  <div class="container">
    <div class="user-greeting">
      <h1 class="title">Hey <%=@user.username%></h1>
      <div data-controller="adding-button-for-profile-picture" class="avatar-box update-button position-relative">
        <%if current_user.avatar.attached?%>
          <%=cl_image_tag current_user.avatar.key, class: "avatar-dashboard"%>
        <%else%>
          <%= image_tag "cat-paw.jpg", class: "avatar-dashboard"%>
        <%end%>
        <a data-action="click->adding-button-for-profile-picture#openModal" class="profile-pic-icon" ><i class="fa-solid fa-pencil"></i></a>
        <div data-adding-button-for-profile-picture-target="modal" id="change_avatar" class="avatar-form d-none"> <%= render "form_picture" %></div>

      </div>
    </div>
    <div class="container-first">
      <div class="dropdown">
        <a id="petDropdown" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><i class="fa fa-chevron-circle-down"></i>Your pets</a>
        <div class="dropdown-menu" aria-labelledby="petDropdown">
          <% if @pets.length > 1 %>
            <% @pets.each do |pet| %>
              <a class="dropdown-item" href="/pages/dashboard?pet=<%= pet.id %>"><%= pet.name %></a>
            <% end %>
          <% else %>
            <%= @pets.first.name %>
          <% end %>
        </div>
        <div class="pet-stats">
          <div class="your-pet">
            <%=link_to pet_path(@pet) do%>
              <%= image_tag @pet.picture_url, class:"pet-picture"%>
            <%end%>
            <%= @pet.name%>
          </div>
          <div class="pet-status">
            <div class="status-item">
              <div id="satisfaction-circle" class="donut" style="<%="background: conic-gradient(#e45e05 #{@pet.satisfaction}%, #fff 0 100%);"%>">
              <div id="satisfaction-gap" class="donut__gap"><p align="center">Satisfaction <%=@pet.satisfaction%>%</p></div>
              </div>
            </div>

            <div class="status-item">
              <div class="donut" style="<%="background: conic-gradient(#D9D9D9 #{@pet.food_level}%, #fff 0 100%);"%>">
              <div class="donut__gap"><p align="center">Food Level <br><%=@pet.food_level%>%</p></div>
              </div>
            </div>

            <div class="status-item">
              <div class="donut" style="<%="background: conic-gradient(#D9D9D9 #{@pet.boredom}%, #fff 0 100%);"%>">
              <div class="donut__gap"><p align="center">Boredom <br><%=@pet.boredom%>%</p></div>
              </div>
            </div>

            <div class="status-item">
              <div class="donut" style="<%="background: conic-gradient(#D9D9D9 #{@pet.health}%, #fff 0 100%);"%>">
              <div class="donut__gap"><p align="center">Health <br><%=@pet.health%>%</p></div>
              </div>
            </div>
          </div>
        </div>
      </div>
      <div class="message">
        <h3><%= @random_message %></h3>
      </div>
    </div>
    <div class="container-second">
  <div class="rank-table">
    <h2>Top donations of the month</h2>
    <table class="styled-table">
      <tr>
        <th>Place</th>
        <th>Pet owner</th>
        <th>Pet satisfaction level</th>
        <th>Donated amount</th>
      </tr>

      <% @leaderboard_users.each_with_index do |user, index| %>

        <tr>
          <td>#<%= index + 1 %></td>
          <td> <%= user.username %> </td>
          <td><%= user.pet.satisfaction %></td>
          <td><%= user.accumulated_donations %>€</td>
        </tr>
      <% end  %>
    </table>
    </div>
      <div class="container-right">
        <div class="cards-right">
          <div class="card">
            <div class="card-icon">
              <i class="fas fa-hand-holding-usd"></i>
            </div>
            <div class="card-content">
              <h2 class="card-title">Donated Amount</h2>
              <h5 class="card-number"> <%= current_user.accumulated_donations %>€ </h5>
            </div>
          </div>
          <div class="card">
            <div class="card-icon">
              <i class="fas fa-arrow-up"></i>
            </div>
            <div class="card-content">
              <h2 class="card-title">Place in the rank</h2>
              <h5 class="card-number"> <%= @leaderboard_users.index(@user) + 1 %> </h5>
            </div>
          </div>
        </div>
        <div class="history">
          <p>History</p>
          <div class="activity-graph">
            <%= column_chart current_user.paid_orders.group_by_month(:created_at, format: "%b").sum(:euro),
            min: 0, max: 30, width: "500px", height: "180px",
            stacked: true, discrete: true, label: "Amount", prefix: "€",
            decimal: ",", round: 2, zeros: true, loading: "Loading...",
            empty: "No data", refresh: 320 %>
        </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/pages/faq.html.erb
<div class="page-content d-flex mb-2 header-faq">
<div class="page-title ">
<h3 class=>FAQ</h3>
  <p>Find the question that interests you </p>
</div>
</div>
<div class="accordion" id="accordionPanelsStayOpenExample">
  <div class="accordion-item">
    <h2 class="accordion-header">
      <button class="accordion-button" type="button" data-bs-toggle="collapse" data-bs-target="#panelsStayOpen-collapseOne" aria-expanded="true" aria-controls="panelsStayOpen-collapseOne">
        Do I actually donate real items for the animals in shelters ?
      </button>
    </h2>
    <div id="panelsStayOpen-collapseOne" class="accordion-collapse collapse show">
      <div class="accordion-body">
        When you choose to donate to a shelter, it will receive only the amount you selected. This money will be used for getting a meal, a medicine, or any other type of item or service needed, but the final choice depends on the shelter itself.
      </div>
    </div>
  </div>
  <div class="accordion-item">
    <h2 class="accordion-header">
      <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#panelsStayOpen-collapseTwo" aria-expanded="false" aria-controls="panelsStayOpen-collapseTwo">
        How can I contact Furry Friend Member Support?
      </button>
    </h2>
    <div id="panelsStayOpen-collapseTwo" class="accordion-collapse collapse">
      <div class="accordion-body">
        Member Support can be reached at<strong> +34 654 654 654 </strong>,but please review the FAQs below to see if the information you're looking for has been addressed.
      </div>
    </div>
  </div>
  <div class="accordion-item">
    <h2 class="accordion-header">
      <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#panelsStayOpen-collapseThree" aria-expanded="false" aria-controls="panelsStayOpen-collapseThree">
        How can I find information and resources for shelter professional?
      </button>
    </h2>
    <div id="panelsStayOpen-collapseThree" class="accordion-collapse collapse">
      <div class="accordion-body">
       Furry Friends can help you . </div>
    </div>
  </div>
</div>

app/views/pages/home.html.erb
<div class="homepage-bg">
  <div class="home-container">
    <div class="banner">
      <div class="banner-content text-center">
        <h1>Furry Friend <br>
        your donations never end !</h1>
        <p style="margin-bottom: 40px;">Donate.Play.Support.</p>
        <%= link_to "Find a shelter", shelters_path, class:"primary-button " %>

      </div>
    </div>

    <div class="container">
      <div class="row justify-content-center">
        <div class="col-md-4">
          <div class="overview-card text-center">
            <i class="fas fa-donate card-icon"></i>
            <h2 class="card-title">+8500€</h2>
            <p>Donated</p>
          </div>
        </div>
        <div class="col-md-4">
          <div class="overview-card text-center">
            <i class="fas fa-users card-icon"></i>
            <h2 class="card-title">+354</h2>
            <p>Collaborators </p>
          </div>
        </div>
        <div class="col-md-4">
          <div class="overview-card text-center">
            <i class="fas fa-home card-icon"></i>
            <h2 class="card-title">+468</h2>
            <p>Animals saved</p>
          </div>
        </div>
      </div>
    </div>

    <section class="value-prop-section container" style="margin-bottom: 120px; margin-top: 120px; ">
      <h2 class="value-prop-heading text">Our Value Proposition</h2>
      <p class="text-center">We provide support not only to animals in need,<br>
      but also to owners who didn’t have experience with a pet before.</p>

      <div class="grid-cont">
        <div class="primary-card">
          <h3>Virtual pet</h3>

          <!-- Button trigger modal -->
          <button type="button" class="round-button" data-bs-toggle="modal" data-bs-target="#staticBackdrop1">
            <i class="fa-solid fa-plus"></i>
          </button>

          <!-- Modal -->
          <div class="modal fade" id="staticBackdrop1" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="staticBackdropLabel1" aria-hidden="true">
            <div class="modal-dialog modal-dialog-centered">
              <div class="modal-content" style="border-radius: 10px; padding: 20px; position: relative;">
                <div class="modal-header">
                  <h1 class="modal-title fs-5" id="staticBackdropLabel1">Virtual pet</h1>
                  <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body">
                  <div class="mb-3">
                    <h3>Get your virtual pet!</h3>
                    <p>With FurryFriend, you can adopt a virtual pet that you can feed, buy toys for, and make sure his health is good! All the money you spend for your pet will be transferred to the shelters that you select nearby you. You can see the rating of all virtual pets and if your pet is on top of it.</p>
                    <h4>Features:</h4>
                    <ul>
                      <li style="font-size: 18px;">Feeding</li>
                      <li style="font-size: 18px;">Buying toys</li>
                      <li style="font-size: 18px;">Monitoring health</li>
                    </ul>
                  </div>
                  <div class="text-center">
                    <%= image_tag "sleep.gif", alt: "Virtual Pet", style: "max-width: 200px; height: auto;" %>
                  </div>
                </div>
                <div class="modal-footer">
                  <button type="button" class="tertiary-button"><%= link_to "Adopt a virtual pet", shelters_path %></button>
                </div>
                <div class="gradient-overlay"></div>
              </div>
            </div>
          </div>
        </div>
        <div class="vp-card">
          <h3> Adopt </h3>
          <!-- Button trigger modal -->
          <button type="button" class="round-button" data-bs-toggle="modal" data-bs-target="#staticBackdrop2">
            <i class="fa-solid fa-plus"></i>
          </button>

          <!-- Modal -->
          <div class="modal fade" id="staticBackdrop2" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="staticBackdropLabel2" aria-hidden="true">
            <div class="modal-dialog modal-dialog-centered">
              <div class="modal-content" style="border-radius: 10px; padding: 20px;">
                <div class="modal-header">
                  <h1 class="modal-title fs-5" id="staticBackdropLabel2">Adopt</h1>
                  <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body">
                  <h3 class="mb-3">Consider adopting a furry friend!</h3>
                  <p>If you have the opportunity to welcome a real pet into your home, we encourage you to consider adoption. By adopting from a shelter, not only are you providing a loving home to a deserving animal, but you're also supporting shelters and rescue organizations in their mission to care for animals in need.</p>
                  <p>When you adopt, you're making a difference in the lives of animals who are still waiting for their forever homes. Take the time to visit your local shelter or rescue organization's website to find your future pet. And remember, even if you can't adopt right now, you can still contribute by donating to help support animals in need.</p>
                  <div class="text-center">
                    <%= image_tag "adopt.gif", alt: "Virtual Pet", style: "max-width: 200px; height: auto;" %>
                  </div>
                </div>
                <div class="modal-footer">
                  <button type="button" class="tertiary-button"><%= link_to "Find a shelter", shelters_path %></button>
                </div>
              </div>
            </div>
          </div>
        </div>
        <div class="vp-card">
          <h3> Connect </h3>
          <!-- Button trigger modal -->
          <button type="button" class="round-button" data-bs-toggle="modal" data-bs-target="#staticBackdrop3">
            <i class="fa-solid fa-plus"></i>
          </button>

          <!-- Modal -->
          <div class="modal fade" id="staticBackdrop3" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="staticBackdropLabel3" aria-hidden="true">
            <div class="modal-dialog modal-dialog-centered">
              <div class="modal-content" style="border-radius: 10px;">
                <div class="modal-header">
                  <h1 class="modal-title fs-5" id="staticBackdropLabel3">Connect</h1>
                  <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body text-left" style="padding: 20px;">
                  <h3 style="font-size: 24px; margin-bottom: 20px;">Connect with others to support animals in need!</h3>
                  <p style="font-size: 18px; margin-bottom: 10px;">We provide different chatrooms where you can:</p>
                  <ul style="font-size: 18px;">
                    <li>Connect with other people who share your passion for animal welfare</li>
                    <li>Offer assistance to animals in need</li>
                    <li>Share your experiences and advice with others</li>
                    <li>Collaborate on various initiatives to support animal shelters and rescue organizations</li>
                  </ul>
                  <div class="text-center my-4">
                    <script src="https://unpkg.com/@dotlottie/player-component@latest/dist/dotlottie-player.mjs" type="module"></script>
                    <dotlottie-player src="https://lottie.host/144a6366-55c5-4a25-a62f-1390cee2a218/YN3kWXCMBb.json" background="transparent" speed="1" style="width: 200px; height: 200px; margin: 0 auto;" loop autoplay></dotlottie-player>
                  </div>
                </div>
                <div class="modal-footer">
                  <button type="button" class="tertiary-button"><%= link_to "Go to the chat", chatroom_path(1) %></button>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
    </section>

    <section class="join_us", style="margin-bottom: 120px;" >
      <div class="text-center">
        <h2>Join us</h2>
        <p style="margin-bottom: 40px;">Supporting animals in need </p>
        <%= link_to "Join now", shelters_path, class:"primary-button" %>
      </div>
    </section>
</div>